services:
  postgres:
    image: postgres:16
    container_name: hotbray_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hotbray
    ports:
      - "5432:5432"
    volumes:
      - hotbray_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: hotbray_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  hotbray_pgdata:
